package com.example.myapplication.model

import androidx.room.Entity
import androidx.room.PrimaryKey

// Defines the Note entity for the Room database
// @Entity annotation specifies that this class represents a table in the database
// - tableName: The name of the table in the database
@Entity(tableName = "notes")
data class Note(
    // Defines the primary key for the table
    // @PrimaryKey annotation marks this field as the primary key
    // - autoGenerate: If true, the primary key value will be automatically generated by Room
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    // Content of the note
    // This field will be stored as a column in the notes table
    val content: String,

    // Category of the note
    // This field will be stored as a column in the notes table
    val category: String,

    // Timestamp indicating when the note was created or last updated
    // This field will be stored as a column in the notes table
    // Default value is the current system time in milliseconds
    val timestamp: Long = System.currentTimeMillis()
)